'use client';
import dynamic from 'next/dynamic';
import {useEffect,useRef,useState} from 'react';
import {ArrowUpRight,ArrowRight,Box,Globe2,Atom,ScanLine,Radio,Layers3,RotateCcw,Pause,Play,Download,ChevronDown,X,Info,Move3D} from 'lucide-react';
import {initialDetectors,predict,optimize} from '@/lib/model.mjs';
const Scene=dynamic(()=>import('./scene'),{ssr:false,loading:()=> <div className="loading">INITIALIZING RESERVOIR<span/></div>});
const modes=[{name:'Digital Twin',icon:Box},{name:'Particle Lab',icon:Atom},{name:'AI Twin',icon:ScanLine},{name:'Detector Lab',icon:Radio},{name:'Earth',icon:Globe2}];
function Range({label,value,min,max,step=1,unit='',onChange}:{label:string;value:number;min:number;max:number;step?:number;unit?:string;onChange:(n:number)=>void}){return <label className="range"><span>{label}<b>{value} {unit}</b></span><input type="range" min={min} max={max} step={step} value={value} onChange={e=>onChange(+e.target.value)}/></label>}
export default function Instrument(){
 const [mode,setMode]=useState('Digital Twin'),[entered,setEntered]=useState(false),[layer,setLayer]=useState(true),[opacity,setOpacity]=useState(15),[slice,setSlice]=useState(0),[particles,setParticles]=useState(true),[playing,setPlaying]=useState(true),[field,setField]=useState('Saturation'),[depth,setDepth]=useState(700),[area,setArea]=useState(3),[exposure,setExposure]=useState(30),[detectors,setDetectors]=useState(initialDetectors),[selected,setSelected]=useState(0),[cameraKey,setCameraKey]=useState(0),[particle,setParticle]=useState<number|null>(null),[method,setMethod]=useState(false),[optimized,setOptimized]=useState(false);
 const [sensors,setSensors]=useState({seismic:true,muon:true,well:true,sar:false});
 useEffect(()=>{if(window.matchMedia('(prefers-reduced-motion: reduce)').matches)setPlaying(false)},[]);
 const results=predict({depth,area,exposure,sensors,detectors}),baseline=predict({depth,area,exposure,sensors,detectors:initialDetectors});
 const experiment=useRef({depth,area,exposure,sensors,detectors,results});
 experiment.current={depth,area,exposure,sensors,detectors,results};
 useEffect(()=>{
  type Registry={registerTool:(tool:object,options:{signal:AbortSignal})=>void|Promise<void>};
  const registry=(document as Document & {modelContext?:Registry}).modelContext;
  if(!registry?.registerTool)return;
  const lifecycle=new AbortController();
  try{void Promise.resolve(registry.registerTool({name:'read_carbon_experiment',description:'Read current synthetic carbon storage experiment inputs and illustrative outputs. No measured scientific data.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute(input:unknown){if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('Expected an empty object');return {provenance:'synthetic demonstration',...experiment.current}}},{signal:lifecycle.signal})).catch(()=>{});}catch{}
  return ()=>lifecycle.abort();
 },[]);
 function move(axis:'x'|'z',v:number){setDetectors(ds=>ds.map((d,i)=>i===selected?{...d,[axis]:v}:d));setOptimized(false)}
 function exportData(){const blob=new Blob([JSON.stringify({schemaVersion:1,provenance:'Synthetic educational demonstration. No Geant4 or trained AI.',parameters:{depth,area,exposure,sensors,detectors},results},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='carbon-mu-experiment.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 return <main>
 <header><a className="brand" href="#">CARBON <em>μ</em><span>SUBSURFACE INTELLIGENCE</span></a><div className="header-right"><span className="status-dot"/> RESEARCH EXPLORER <span className="version">V.01</span><button className="icon-button" aria-label="About the science" onClick={()=>setMethod(true)}><Info size={18}/></button></div></header>
 <section className="intro"><div><div className="eyebrow"><span/> COSMIC PARTICLES. UNDERGROUND ANSWERS.</div><h1>Beneath the surface.<br/><span>Beyond the uncertainty.</span></h1><p>Can particles from space help reveal where captured carbon goes?<br className="desktop"/> Step inside a carbon storage digital twin and explore the invisible.</p><button className="primary" onClick={()=>{setEntered(true);document.getElementById('instrument')?.scrollIntoView({behavior:'smooth'});}}> {entered?'EXPLORE DIGITAL TWIN':'ENTER DIGITAL TWIN'} <ArrowRight size={16}/></button></div><div className="intro-note"><span className="cross">+</span><p>OBSERVE THE UNSEEN</p><strong>From the atmosphere<br/>to the reservoir.</strong><div className="mini-rule"/><span>An interactive experiment in<br/>carbon storage monitoring.</span></div></section>
 <section className="instrument" id="instrument" aria-label="Carbon storage digital twin">
 <div className="instrument-top"><div className="site"><span className="status-dot"/><b>SLEIPNER</b><span>NORTH SEA, NORWAY</span></div><span className="demo-badge">SYNTHETIC DEMONSTRATION</span></div>
 <nav aria-label="Explorer modes">{modes.map(({name,icon:Icon})=><button key={name} aria-pressed={mode===name} className={mode===name?'active':''} onClick={()=>{setMode(name);if(name==='Particle Lab')setParticles(true);}}><Icon size={16}/>{name}</button>)}<button className="export" onClick={exportData}><Download size={15}/><span>Export experiment</span></button></nav>
 <div className="workspace"><aside className="left-panel"><div className="panel-label">01 / VIEW CONTROLS</div><h2>{mode==='Earth'?'Orbital overview':mode==='Detector Lab'?'Design the experiment':mode==='AI Twin'?'Combine the evidence':mode==='Particle Lab'?'Follow the particles':'Inside the reservoir'}</h2><p className="muted">{mode==='Earth'?'A conceptual locator for the underground experience.':mode==='Detector Lab'?'Explore how placement changes the illustrative signal.':mode==='AI Twin'?'Toggle measurements to explore modeled uncertainty.':mode==='Particle Lab'?'Select a glowing trajectory to inspect a sample muon.':'Peel back the geology. See what lies below.'}</p>
 <div className="panel-section"><label className="toggle"><span><Layers3 size={15}/> Geological layers</span><input type="checkbox" checked={layer} onChange={e=>setLayer(e.target.checked)}/></label><Range label="Layer opacity" value={opacity} min={0} max={70} unit="%" onChange={setOpacity}/><Range label="Remove upper layers" value={slice} min={0} max={5} onChange={setSlice}/></div>
 <div className="panel-section"><span className="label">PLUME FIELD</span><div className="select-wrap"><select aria-label="Plume field" value={field} onChange={e=>setField(e.target.value)}>{['Saturation','Pressure','Uncertainty'].map(v=><option key={v}>{v}</option>)}</select><ChevronDown size={14}/></div><label className="toggle"><span><Atom size={15}/> Muon trajectories</span><input type="checkbox" checked={particles} onChange={e=>setParticles(e.target.checked)}/></label></div>
 <div className="panel-section"><span className="label">MEASUREMENT FUSION</span>{(Object.keys(sensors) as (keyof typeof sensors)[]).map(s=><label className="toggle sensor" key={s}><span><i className={s}/>{s==='sar'?'Surface deformation':s==='well'?'Well measurements':s==='muon'?'Cosmic muons':'Seismic surveys'}</span><input type="checkbox" checked={sensors[s]} onChange={e=>setSensors({...sensors,[s]:e.target.checked})}/></label>)}</div><button className="text-button" onClick={()=>setMethod(true)}>How this demonstration works <ArrowUpRight size={13}/></button></aside>
 <div className="scene-wrap"><div className="scene-heading"><span className="label">{mode==='Earth'?'01 / EARTH VIEW':'02 / RESERVOIR VIEW'}</span><h3>{mode==='Earth'?'A planetary perspective':'Utsira formation'}</h3><span>Conceptual geometry · not to scale</span></div><Scene mode={mode} layer={layer} opacity={opacity} slice={slice} particles={particles} playing={playing} field={field} uncertainty={results.uncertainty} depth={depth} detectors={detectors} selected={selected} onSelect={setSelected} onParticle={setParticle} cameraKey={cameraKey}/><div className="scene-legend"><span><i/> CO₂ plume</span><span><i/> Muon trajectory</span><span><i/> Detector</span></div><div className="scene-bottom"><span><Move3D size={13}/> Drag to orbit · Scroll to zoom</span><div><button className="icon-button" aria-label={playing?'Pause particles':'Resume particles'} onClick={()=>setPlaying(!playing)}>{playing?<Pause size={16}/>:<Play size={16}/>}</button><button className="icon-button" aria-label="Reset camera" onClick={()=>setCameraKey(v=>v+1)}><RotateCcw size={15}/></button></div></div>{particle!==null&&<div className="particle-card"><button className="close" aria-label="Close particle" onClick={()=>setParticle(null)}><X size={15}/></button><span className="label">ILLUSTRATIVE PARTICLE</span><h3>Muon #{938400+particle}</h3><p>Momentum <b>{(45+particle*.73).toFixed(1)} GeV/c</b></p><p>Zenith angle <b>{(10+particle*.31).toFixed(1)}°</b></p><p>Sample path <b>{881+particle} m</b></p><small>Animated sample, not a tracked physics event.</small></div>}</div>
 <aside className="right-panel"><div className="panel-label">03 / DETECTOR LAB</div><div className="subheading"><h2>Listen deeper.</h2><Radio size={18}/></div><p className="muted">Configure your virtual detector array.</p><div className="detector-tabs">{detectors.map((_,i)=><button key={i} aria-pressed={selected===i} className={selected===i?'active':''} onClick={()=>setSelected(i)}>D{i+1}</button>)}</div><Range label="Array depth" value={depth} min={300} max={900} step={10} unit="m" onChange={setDepth}/><Range label="Area / detector" value={area} min={1} max={10} unit="m²" onChange={setArea}/><Range label="Exposure" value={exposure} min={1} max={180} unit="days" onChange={setExposure}/>{mode==='Detector Lab'&&<><Range label={`D${selected+1} · East / west`} value={detectors[selected].x} min={-4} max={4} step={.1} onChange={v=>move('x',v)}/><Range label={`D${selected+1} · North / south`} value={detectors[selected].z} min={-2.5} max={2.5} step={.1} onChange={v=>move('z',v)}/></>}
 <div className="rate"><span className="label">ILLUSTRATIVE MUON RATE / DETECTOR</span><strong>{results.rate.toFixed(2)}<span>events / day</span></strong><div className="bars" role="img" aria-label="Illustrative cumulative expected events over the selected exposure">{Array.from({length:28},(_,i)=><i key={i} style={{height:`${(i+1)/28*100}%`}}/>)}</div><small>{results.events.toLocaleString()} expected events per detector over {exposure} days</small></div><button className="primary optimize" onClick={()=>{setDetectors(optimize());setOptimized(true);setMode('Detector Lab')}}><ScanLine size={15}/> OPTIMIZE DETECTORS <ArrowUpRight size={14}/></button><p className="optimization-note" aria-live="polite">{optimized?`Demo placement applied · ${(baseline.uncertainty-results.uncertainty).toFixed(1)} percentage points lower uncertainty than the starting array.`:'Illustrative placement heuristic · no trained AI'}</p></aside></div>
 <div className="metrics" aria-live="polite"><div><span className="label">RECONSTRUCTION UNCERTAINTY</span><strong>{results.uncertainty.toFixed(1)}<em>%</em><span className="metric-tag">DEMO</span></strong><div className="meter"><i style={{width:results.uncertainty+'%'}}/></div></div><div><span className="label">INFORMATION SCORE</span><strong>{results.information.toFixed(2)}<em>bits</em></strong><small>Illustrative evidence score</small></div><div><span className="label">ACTIVE MEASUREMENTS</span><strong>{Object.values(sensors).filter(Boolean).length}<em>/ 4</em></strong><small>Independent input toggles</small></div><div><span className="label">VIRTUAL DETECTOR ARRAY</span><strong>03<em>detectors</em></strong><small>{depth} m depth · {area} m² each</small></div></div>
 {mode==='AI Twin'&&<div className="comparison"><div><span className="label">SYNTHETIC REFERENCE</span><h3>A known conceptual plume</h3><div className="distribution reference"/><p>Fixed reference geometry used only for this demonstration.</p></div><div><span className="label">ILLUSTRATIVE RECONSTRUCTION</span><h3>More evidence. Less uncertainty.</h3><div className="distribution" style={{opacity:1-results.uncertainty/130,filter:`blur(${results.uncertainty/8}px)`}}/><p>Uncertainty band: {results.uncertainty.toFixed(1)}%. Toggle measurement sources to compare.</p></div></div>}
 </section><section className="science-note"><span className="note-index">μ /</span><div><h3>A new perspective on what we cannot see.</h3><p>This prototype explores the idea of combining cosmic muons with other measurements to investigate underground carbon storage. Geometry, particle paths, and numerical results are synthetic. They are not Sleipner observations or validated scientific predictions.</p></div><button onClick={()=>setMethod(true)}>READ THE METHODOLOGY <ArrowUpRight size={16}/></button></section><footer><a className="brand" href="#">CARBON <em>μ</em></a><span>Built for curiosity. Designed for discovery.</span><span>RESEARCH PROTOTYPE / 2026</span></footer>
 {method&&<div className="modal-backdrop" onClick={()=>setMethod(false)}><section className="modal" role="dialog" aria-modal="true" aria-label="Methodology" onClick={e=>e.stopPropagation()} onKeyDown={e=>{if(e.key==='Escape')setMethod(false);if(e.key==='Tab'){e.preventDefault();}}}><button autoFocus className="close" onClick={()=>setMethod(false)} aria-label="Close methodology"><X/></button><span className="eyebrow">THE SCIENCE / THE PROTOTYPE</span><h2>Explore a hypothesis.</h2><p>This is an educational instrument with procedural geometry and an explicit mathematical demo model. It does not run Geant4, use measured Sleipner data, or perform AI inference.</p><h3>What changes the results?</h3><p>The illustrative rate is 12 × area × exp(−depth / 270). Exposure scales expected counts. Measurement toggles and detector proximity to the plume contribute to an evidence score. Uncertainty decreases as this score grows. These relationships are selected for demonstration, not calibrated to real rock or detector response.</p><h3>What does optimization do?</h3><p>A deterministic heuristic places three detectors near the conceptual plume. It is not an expected information gain search or a trained experiment designer.</p><h3>Path to a scientific instrument</h3><p>Replace the demo model with validated precomputed Geant4 detector responses, measured geology, and calibrated reconstruction outputs. Keep heavy scientific computation outside the web hosting environment. The exported JSON preserves the inputs and labels the provenance.</p></section></div>}
 </main>
}
